services:
  sinha_db:
    container_name: sinha_mongoDB
    image: mongo
    networks:
      - main_network
    ports:
      - "27017:27017"
  sinha_backend:
    container_name: sinha_backend_app
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "9099:9099"
    depends_on:
      - sinha_db
    networks:
      - main_network
  sinha_frontend:
    container_name: sinha_frontend_app
    build: 
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - sinha_backend
    networks:
      - main_network
   

networks:
  main_network:
   